Fix global-node-modules RPM build
PelionIoT/distro-pelion-edge pull request #142
Opened 2021-04-27 09:28 UTC by kbgl

Port `global-node-modules` changes from Debian to RPM build

2021-04-27 15:08 UTC, kunal11191 approved these changes
approving this since rhel and centos jobs are again stable on this branch. 
Please do wait for Ryans approval as well

2021-04-27 15:38 UTC, ryannowarm commented
It might makes sense to add more detail to the commit message.  Something like: "upgrade global-node-modules to be inline with what we use in deb"

2021-04-27 15:39 UTC, ryannowarm requested changes
It might makes sense to add more detail to the commit message. Something like: "upgrade global-node-modules to be inline with what we use in deb"

2021-04-28 15:20 UTC, ryannowarm approved these changes

2021-05-04 13:36 UTC, merged