Add support for distro variants
PelionIoT/distro-pelion-edge pull request #170
Opened 2021-06-16 06:30 UTC by CristianPrundeanuARM

The script now supports creating distro variants (e.g. "buster-next")
based on packages in the base build directory name (e.g. "buster").
This is done automatically, the command line only needs to specify the
destination name (e.g. "--distro=buster-next").

Signed-off-by: Cristian Prundeanu <cristian.prundeanu@pelion.com>

2021-06-16 14:59 UTC, costanic requested changes
I don't understand, these seem like separate things.  `--distro` allows me to specify which build I want to repo-ize and it seems like something else should allow me to override the resulting repo distribution name.  It's confusing to me to combine these concepts into a single parameter.

2021-06-16 15:58 UTC, CristianPrundeanuARM commented
I did this on purpose, to avoid the most common case of entering duplicate information (e.g. input buster, output buster). The case handling gets hairy since distro support is an array, we'd have to keep track of two arrays and match them correctly (i.e. what to do when the number of elements doesn't match - input buster, output buster and buster-next, etc).

The most obvious solution seemed to be to only specify the output, since the input can automatically be determined based on that, and the user really only cares about the output.

2021-06-17 21:31 UTC, costanic approved these changes

2021-06-21 16:05 UTC, CristianPrundeanuARM commented
CI build failed on RHEL because the CI Redhat Enterprise account subscription is no longer active. Merging this as is.

2021-06-21 16:06 UTC, merged