lock down floating Dockerfile base image versions
PelionIoT/distro-pelion-edge pull request #211
Opened 2021-08-18 18:16 UTC by ryannowarm

In order to be able to reproduce a build, every dependency must be
pinned to a specific version and not allowed to float.  Select docker
image tags that don't change.

2021-08-18 20:38 UTC, mray190 requested changes
Needs rebase now that https://github.com/PelionIoT/distro-pelion-edge/pull/210 has been merged (with corresponding changes)

2021-08-18 22:19 UTC, ryannowarm commented
Done

2021-08-19 12:54 UTC, kbgl approved these changes

2021-08-19 13:47 UTC, akazimierskigl approved these changes

2021-08-19 14:01 UTC, mray190 approved these changes

2021-08-19 14:02 UTC, merged